language: r
os: linux
cache: packages

r_binary_packages:
  - covr

r_check_args: "--as-cran --run-dontrun"

after_success:
 - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
